# Generated by Django 6.0.3 on 2026-04-27 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BancoPessoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, upload_to='profiles/')),
                ('name', models.CharField(max_length=60)),
                ('description', models.TextField(max_length=700)),
                ('course', models.CharField(max_length=70)),
                ('period', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=100)),
                ('github', models.URLField()),
                ('linkedin', models.URLField()),
            ],
        ),
    ]
